# Generated by Django 2.1.1 on 2018-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmedia', '0002_updateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediatype',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
